### ISSUE TITLE
Move "Region" parameter from API config to function call parameter

### ISSUE THREAD

**Issue by marclop** [elastic/cloud-sdk-go#103]
### Background
There seems to be an agreement that we're to move away from top level region interpolation in favour of using `region` as a parameter in API calls. We'll eventually have new endpoints which accept `region` as a parameter. 
In the meantime the `/api/v1/platform/...` routes still need an interpolated `/api/v1/regions/<region>/platform/...` in the endpoint to target that specific region.

### Description
To be able to provide a better experience for consumers of the Elastic Cloud SDK, it would be ideal to move away from region-bound `api.API` instances to a region-less instance which can accommodate region-specific calls. 

Doing so will most likely require some modifications to `api.CloudClientRuntime` and most likely the `api.API` structure too. The bigger investment will come to consumers of the SDK will require crafty modifications.

## Possible Implementation

Requires investigation to reach a good API

**Comment by jowiho** [comment]
> There seems to be an agreement that we're to move away from top level region interpolation in favour of using region as a parameter in API calls. We'll eventually have new endpoints which accept region as a parameter.

Though we would certainly like to reconsider the region interpolation in the `/v1/platform` endpoints, we currently don't have concrete plans to change anything. There are simply too many other things that have a higher priority. The current effort is to get rid of the `/v0` and `/v0.1` endpoints first.

Any new endpoints that we introduce in the public API will definitely not use region interpolation.
