### ISSUE TITLE
Releasing new version of cloud sdk

### ISSUE THREAD

**Issue by ggsood** [elastic/cloud-sdk-go#221]
Hi all

The current master version of cloud sdk supports observability settings for Elastic cloud deployments, whereas these settings are not available in the current release.

Any plans for releasing the new sdk version.

Thanks

**Comment by karencfv** [comment]
Thanks for the question @ggsood 🙇‍♀️ 

At the moment some of the changes in our apidocs have not been rolled out to production on Elastic Cloud, so we can't release a new version just yet. We'll release as soon as we can.

**Comment by ggsood** [comment]
Hi @karencfv 

Thanks for the update, i was just checking the new Elastic cloud console and i can see the new observability settings present there, the code in sdk has the implementation too, 🤞 we have a release soon.

**Comment by karencfv** [comment]
@ggsood, Unfortunately we need all of these features to be available in our [ECE](https://www.elastic.co/ece) product as well. We will be releasing alongside ECE 2.7
