### ISSUE TITLE
Example in README.md is broken

### ISSUE THREAD

**Issue by wandergeek** [elastic/cloud-sdk-go#256]
## Readiness Checklist
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior
List deployment example in README.md should compile. 

## Current Behavior
```
$ go run main.go
# command-line-arguments
./main.go:24:58: cannot use ess.V1API (type *"github.com/elastic/cloud-sdk-go/pkg/client".Rest) as type *api.API in field value
```

## Steps to Reproduce
1.  Add code from README.md to main.go.
2. go run main.go

## Context
Unable to get started with cloud-sdk.

**Comment by marclop** [comment]
sorry for the late fix, I've opened a PR (linked) which should address this issue.

**Comment by wandergeek** [comment]
Thanks mate!
