### ISSUE TITLE
stackapi: List not ordered correctly

### ISSUE THREAD

**Issue by karencfv** [elastic/cloud-sdk-go#259]
## Readiness Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior
When using the `stackapi.List` API a list of the available stack packs should be returned
ordered from latest to oldest.

## Current Behavior
With version `7.10.0` out the list is now ordered in the following way:

```console
VERSION   DELETED   ELASTICSEARCH IMAGE                                     KIBANA IMAGE                                     APM IMAGE
7.9.3     false     docker.elastic.co/cloud-assets/elasticsearch:7.9.3-0    docker.elastic.co/cloud-assets/kibana:7.9.3-0    docker.elastic.co/cloud-assets/apm:7.9.3-0
<...>
7.2.0     false     docker.elastic.co/cloud-assets/elasticsearch:7.2.0-0    docker.elastic.co/cloud-assets/kibana:7.2.1-1    docker.elastic.co/cloud-assets/apm:7.2.0-0
7.10.0    false     docker.elastic.co/cloud-assets/elasticsearch:7.10.0-0   docker.elastic.co/cloud-assets/kibana:7.10.0-0   docker.elastic.co/cloud-assets/apm:7.10.0-0
7.1.1     false     docker.elastic.co/cloud-assets/elasticsearch:7.1.1-0    docker.elastic.co/cloud-assets/kibana:7.1.1-1    docker.elastic.co/cloud-assets/apm:7.1.1-0
```

## Context
Both ecctl and terraform-provider-ec use the first version returned to fill in default
"lastest" values for versions.

**Comment by marclop** [comment]
We probably need to use the `semver` dependency to parse each of the versions and compare them.
