### ISSUE TITLE
Update plan tracker and vacate errors to include new API fields

### ISSUE THREAD

**Issue by marclop** [elastic/cloud-sdk-go#278]
## Overview

With MS53, we're going to ship new fields in the plan models so the API spec needs to be updated and make a bunch of changes related to these fields being bubbled up:

* Plan Tracker
* Vacate JSON errors.

**Comment by marcinpm** [comment]
@marclop , @cstrzadala is there any chance this issue  can get picked up and prioritized, please? I recently found out it is a blocker us as we want to get proper error codes for vacate issues (which currently mostly coming as unknown). 
There's a bit of context on this [here](https://github.com/elastic/cloud/issues/71631#issuecomment-777360831) and I mentioned this in my [PSI doc](https://docs.google.com/document/d/15Is3jOjAhJ9Je88ji9zvTtys24DP95G5Caobxmtwn9U/edit#).

**Comment by marclop** [comment]
@marcinpm I'll take a look and make the necessary changes since I've already been making changes to the SDK these days.

**Comment by marcinpm** [comment]
Awesome, many thanks @marclop!
