### ISSUE TITLE
NewUpdateReq - support for node_roles in >=7.10

### ISSUE THREAD

**Issue by neiljbrookes** [elastic/cloud-sdk-go#309]
## Readiness Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

That `deploymentapi.NewUpdateRequest()` returns a valid  DeploymentUpdateRequest for _all_ version.

## Current Behavior

Using a new `DeploymentUpdateRequest` from `deploymentapi.NewUpdateRequest()` gives an error for clusters >=7.10 (my test deployment was 7.11).

```
error updating deployment: api error: 4 errors occurred:
	* clusters.cluster_invalid_plan: Cluster must contain at least a master topology element and a data topology element. 'master' node type is missing,'data' node type is missing,'master' node type exists in more than one topology element (resources.elasticsearch[0].cluster_topology)
	* clusters.cluster_invalid_plan: Node types are not specified for the cluster topology. You must specify at least one of available node types: [data,master,ingest]. (resources.elasticsearch[0].cluster_topology[0].node_type)
	* deployments.missing_topology_element: Deployment plan definition with template [I/O Optimized] missing topology element with instance configuration: [Some(aws.data.highio.i3)], node type: [Some(ElasticsearchNodeType(Some(true),Some(true),Some(true),None))] (resources.elasticsearch[0])
	* deployments.unrecognized_topology_elements: Deployment plan definition includes topology element not supported by template [I/O Optimized]. Instance configuration: [Some(aws.data.highio.i3)], node types: [None] (resources.elasticsearch[0])
```

## Steps to Reproduce

1. Create a 7.11 deployment
2. GET a `DeploymentGetResponse` for this deployment. 
```golang
ok, err := ifs.CloudSDKDeployments.GetDeployment(getParams, ifs.CloudSDKAuthInfo)
if err != nil {
	return err
}
res := ok.GetPayload()
```
3. Use `NewUpdateRequest` to generate a `DeploymentUpdateRequest`
```golang
newReq := deploymentapi.NewUpdateRequest(res)
```
4. Update the deployment and see errors
```golang
params := deployments.NewUpdateDeploymentParams().
		WithDeploymentID(deploymentID).
		WithBody(req)
_, err = ifs.CloudSDKDeployments.UpdateDeployment(params, ifs.CloudSDKAuthInfo)
```

## Your Environment

* Version used: 1.2.0
* Environment name and version (e.g. Go 1.9): 
* Server type and version:
* Operating System and version:
* Link to your project:

cc @marclop. Pretty sure this is the same `node_type` v's `node_role` change that I saw you implementing support for in the terraform provider !

**Comment by marclop** [comment]
@neiljbrookes what version of the SDK are you using?

**Comment by neiljbrookes** [comment]
Thanks @marclop. I was indeed using 1.2.0.
I see that 1.3.0 is tagged now (https://github.com/elastic/cloud-sdk-go/releases/tag/v1.3.0) so I pulled the updated version and tested successfully with both <=7.10 and >=7.10.

Closing this now.
