### ISSUE TITLE
Preserve empty topology elements with NewUpdateRequest when autoscaling is true

### ISSUE THREAD

**Issue by neiljbrookes** [elastic/cloud-sdk-go#366]
## Readiness Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

Passing a `GetDeploymentResponse` to `NewUpdateRequest` will create a valid `DeploymentUpdateRequest` when deployment autoscaling is enabled.

## Current Behavior

Currently the `NewUpdateRequest` function will exclude topology elements were `MemoryPerNode = 0`

https://github.com/elastic/cloud-sdk-go/blob/62f7d2b2ab9eb1757dba181ae6bb656745f9c5c3/pkg/api/deploymentapi/update_payload.go#L100

When operating on deployments with `autoscaling : true` this will remove _valid_ topology elements, and return an error like this

```
"Deployment plan definition with template [I/O Optimized] missing topology elements: [coordinating,warm,cold]. Only [hot_content,frozen,master,ml] was supplied."
```

## Possible Solution

Check for deployment autoscaling before removing topology elements.

## Steps to Reproduce

1. `GetDeploymentResponse` from a deployment with autocaling enabled
2. Create a `DeploymentUpdateRequest` with `NewUpdateRequest(res)`
3. Attempt to no-op
4. Recieve error

## Context

We use `NewUpdateRequest` in our tooling to easily generate update payloads.

## Your Environment

* Version used: v1.6.0
* Environment name and version (e.g. Go 1.9): go1.16.3 darwin/amd64
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by neiljbrookes** [comment]
Relevant docs : https://www.elastic.co/guide/en/cloud-enterprise/current/ece-autoscaling-api-example.html

```
All Elasticsearch components must be included in the request, even if they are not enabled (that is, if they have a zero size)
```

**Comment by henrikno** [comment]
Fixed by https://github.com/elastic/cloud-sdk-go/pull/416
